before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: gqbPwskCpK9u1JI1AupKOYGW+8Puhri//8rdXOj6V8KbWhI/13tpkoo5OELsmUsRElh8liZnp/q3Ov9jBQPHIC2iQMTrzm4nT8LvT7QnKTVKDVzu9/CS82j148HrtPutdSW0rsyHZKUQlXJtu+hqTdz7LQP829UbnLEhr0IMY3dgoEw9M3ZZ7VXRUE/vgLzbLZfwlKcVaJVK6jdLFtGfFSgClqVHlsPcojADvrMnaEJuTc/V1SHMaig1RGAxRmJH4brlkkZlaUq2WXwuE1q0nNsFvwxdh4dtE4SUxsOrlbmN+nU2lgRvGpUN6DrQ/KaWZQqldSKn7BNadwDhbWI+BhSaHyH2ZV+x7lrdT2fwKN492STCyNH5qh+1PS1cZJnPzgygBoN4M1jHy02tVPZanQGrgHlFa5N/p4+iLH2y6oSqm779q/3s5SjZF3APKLQGlSPWHXAwn9VnX3r9l2AD4ncJuJVWyMUrnCPmXCrOVxHUjeXo1cSdsQPSDPozDRVl/FMCWnYK0uKwrLt6a6EfXINDVN/neVaBtk2p+yKpALXcLgZ7ySmVip4UvdWse/aL9JRbhoalm6A1vxPPOQdLQvVImbtOS4EbW6aHc8JuXp1EKhATJ4w0uZIkPhbhLJwG53Yo28D6OZBMTmgyDwBUjDJ5km3ZPBmgr1x48OFdMtk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
